version: "3.7"
services:
  patron_erp_app:
    build:
      args:
        user: SkylarkSoft
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: patron-erp
    container_name: patron-erp-application
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
      - ./.docker/app/php-fpm.ini:/usr/local/etc/php/conf.d/99-app.ini
    env_file:
      - ./.env
    depends_on:
      - patron_erp_database
    links:
      - patron_erp_database
    networks:
      - patron-erp-network
  patron_erp_nginx:
    image: nginx:alpine
    container_name: patron-erp-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - patron-erp-network
    depends_on:
      - patron_erp_database
      - patron_erp_phpmyadmin
  patron_erp_database:
    image: mysql:8.0.2
    container_name: patron-erp-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - patron-erp-network
  patron_erp_phpmyadmin:
    image: phpmyadmin
    container_name: patron-erp-phpmyadmin
    restart: always
    tty: true
    depends_on:
      - patron_erp_database
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: patron_erp_database
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 2048M
    networks:
      - patron-erp-network

networks:
  patron-erp-network:
    driver: bridge
